r"""ArduPilot layer: the flight-controller artifacts for the specific vehicle.

Two honest deliverables:
  - specimen.param  : a REAL, design-specific ArduCopter parameter set (frame, battery, ESC, motors,
                      seeker/gimbal mount, failsafes) generated from cfg. This is the artifact you load
                      into the vehicle — it is what makes generic ArduCopter firmware into THIS aircraft.
  - arducopter.apj  : the REAL official ArduCopter firmware for the chosen board, downloaded from
                      firmware.ardupilot.org. Firmware is standard per board (not design-authored), so the
                      honest package includes the official release + a provenance manifest (URL, git id,
                      sha256). It is NOT compiled here (no ARM toolchain / no sudo) and NOT fabricated.

Board default: CubeOrange (a Pixhawk-standard autopilot). Configurable.
"""
from __future__ import annotations

import hashlib
import json
import os
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
FW_BASE = "https://firmware.ardupilot.org/Copter/stable"


def gen_param(cfg, out_dir, board="CubeOrange", vehicle="quad-seeker"):
    """Generate a real ArduCopter .param from the design vector. Returns path."""
    S = int(cfg["S"])
    v_full, v_low, v_crt = S * 4.2, S * 3.5, S * 3.3
    # hover throttle ~ 1/TWR (thrust needed to hover / max thrust). Fallback 0.35.
    twr = cfg.get("_TWR", 2.5)
    hover = max(0.15, min(0.6, 1.0 / twr))
    P = [
        ("# ArduCopter parameters — generated by SpecimenLab for " + vehicle, None),
        ("# board: " + board, None),
        ("FRAME_CLASS", 1),          # Quad
        ("FRAME_TYPE", 1),           # X
        ("ARMING_CHECK", 1),
        ("AHRS_EKF_TYPE", 3),
        ("EK3_ENABLE", 1),
        ("INS_ACCEL_FILTER", 20),
        # --- battery ---
        ("BATT_MONITOR", 4),         # voltage+current
        ("BATT_CAPACITY", int(cfg["cap_mAh"])),
        ("BATT_LOW_VOLT", round(v_low, 1)),
        ("BATT_CRT_VOLT", round(v_crt, 1)),
        ("BATT_FS_LOW_ACT", 2),      # RTL
        ("BATT_FS_CRT_ACT", 1),      # Land
        ("MOT_BAT_VOLT_MAX", round(v_full, 1)),
        ("MOT_BAT_VOLT_MIN", round(v_crt, 1)),
        ("MOT_BAT_CURR_MAX", round(cfg["I_max"] * cfg["n_rotors"], 0)),
        # --- ESC / motors ---
        ("MOT_PWM_TYPE", 6),         # DShot600
        ("MOT_SPIN_ARM", 0.10),
        ("MOT_SPIN_MIN", 0.15),
        ("MOT_THST_HOVER", round(hover, 3)),
        ("MOT_THST_EXPO", 0.65),
        # --- servo outputs (quad X on 1..4, DShot) ---
        ("SERVO1_FUNCTION", 33), ("SERVO2_FUNCTION", 34),
        ("SERVO3_FUNCTION", 35), ("SERVO4_FUNCTION", 36),
        # --- seeker / camera gimbal on mount 1 (servo gimbal, outputs 9/10/11) ---
        ("MNT1_TYPE", 1),
        ("MNT1_PITCH_MIN", -90), ("MNT1_PITCH_MAX", 20),
        ("MNT1_YAW_MIN", -180), ("MNT1_YAW_MAX", 180),
        ("MNT1_RC_RATE", 30),
        ("SERVO9_FUNCTION", 7),      # mount pitch
        ("SERVO10_FUNCTION", 6),     # mount roll
        ("SERVO11_FUNCTION", 8),     # mount yaw
        ("CAM1_TYPE", 1),
        # --- failsafes ---
        ("FS_THR_ENABLE", 1),
        ("FS_GCS_ENABLE", 1),
        ("FENCE_ENABLE", 1),
        ("RTL_ALT", 3000),
        # --- pilot / nav defaults sized modestly for a seeker quad ---
        ("WPNAV_SPEED", 800),
        ("PILOT_SPEED_UP", 250),
        ("ANGLE_MAX", 4000),
    ]
    path = os.path.join(out_dir, "specimen.param")
    os.makedirs(out_dir, exist_ok=True)
    with open(path, "w", newline="\n") as f:
        for k, v in P:
            if v is None:
                f.write(k + "\n")
            else:
                f.write(f"{k},{v}\n")
    return path, sum(1 for _, v in P if v is not None)


def fetch_firmware(out_dir, board="CubeOrange", timeout=120):
    """Download the official ArduCopter .apj for the board via WSL curl. Returns manifest dict."""
    os.makedirs(out_dir, exist_ok=True)
    import openfoam_runner as ofr
    url = f"{FW_BASE}/{board}/arducopter.apj"
    dst = os.path.join(out_dir, "arducopter.apj")
    wdst = ofr.win_to_wsl(dst)
    p = subprocess.run(["wsl.exe", "-e", "bash", "-lc",
                        f"curl -fsSL --max-time {timeout} '{url}' -o '{wdst}' && echo __DL_OK__"],
                       capture_output=True, text=True, timeout=timeout + 20)
    if "__DL_OK__" not in (p.stdout + p.stderr) or not os.path.exists(dst):
        return {"ok": False, "reason": (p.stderr or p.stdout)[-160:], "url": url}
    raw = open(dst, "rb").read()
    sha = hashlib.sha256(raw).hexdigest()
    meta = {}
    try:
        j = json.loads(raw.decode("utf-8", "ignore"))
        meta = {kk: j.get(kk) for kk in ("board_id", "magic", "description",
                                         "image_size", "flash_total", "git_identity", "version")}
    except Exception:
        pass
    manifest = {"ok": True, "board": board, "source": url, "provenance": "official ArduPilot release (downloaded, not tool-generated)",
                "file": "arducopter.apj", "bytes": len(raw), "sha256": sha, **meta}
    with open(os.path.join(out_dir, "firmware_manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)
    return manifest


if __name__ == "__main__":
    cfg = dict(D_in=15, pitch_in=7, Kv=340, I_max=45, S=6, cap_mAh=5000, C_rate=60,
               L_arm=0.30, payload=0.6, n_rotors=4, _TWR=2.5)
    out = os.path.join(HERE, "build_specimen", "ardupilot")
    pp, npar = gen_param(cfg, out)
    print("param:", pp, "(", npar, "params )")
    fw = fetch_firmware(out)
    print("firmware:", json.dumps(fw, indent=2)[:500])
